pim_enrich_attributegroup_rest_index:
    path: '/'
    defaults: { _controller: pim_enrich.controller.rest.attribute_group:indexAction }
    methods: [GET, POST]

pim_enrich_attributegroup_rest_get:
    path: /{identifier}
    defaults: { _controller: pim_enrich.controller.rest.attribute_group:getAction }
    methods: [GET]
    requirements:
        identifier: '[a-zA-Z0-9_]+'

pim_enrich_attributegroup_rest_post:
    path: /{identifier}
    defaults: { _controller: pim_enrich.controller.rest.attribute_group:postAction }
    methods: [POST]
    requirements:
        identifier: '[a-zA-Z0-9_]+'
